services:
  - type: web
    name: comprovante-guimicell-bot
    env: python
    region: oregon
    plan: free
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: TOKEN
        sync: false
      - key: GROUP_ID
        sync: false
