services:
  - type: web
    name: comprovante-guimicell-bot
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: python3 main.py
    envVars:
      - key: PORT
        value: 10000
