services:
  - type: web
    name: bot-comprovante-dbh
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: "python3 main.py"
    envVars:
      - key: PORT
        value: 10000
