services:
  - type: web
    name: comprovantes
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: PORT
        value: 10000
