services:
  - type: web
    name: comprovantes-bot
    runtime: python
    buildCommand: ""
    startCommand: python3 main.py
    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: GROUP_ID
        sync: true
      - key: PORT
        sync: true
